layout_spectrum: 0.08466566
typography_spectrum: 0.5259467
color:
  saturation: 0.3886836
  lightness: 0.9723961
  brandStrength: 0.8962831
  rhythmicContrast: 0.2057549
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Aatash
